# $FreeBSD: doc/hu_HU.ISO8859-2/slides/Makefile,v 1.2 2008/06/25 11:28:11 gabor Exp $
# %SOURCE%    en_US.ISO8859-1/slides/Makefile
# %SRCID%     1.1

SUBDIR= freebsd-general

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
