#!/bin/sh

# $Wintelcom: src/freebsd/pxe/doc/pre,v 1.1 2000/07/14 12:42:05 bright Exp $
# $FreeBSD: doc/da_DK.ISO8859-1/articles/pxe/pre,v 1.1 2003/12/31 12:46:33 blackend Exp $

echo pre-install
exit 0
