# $FreeBSD: www/it/ports/Makefile,v 1.1 2006/06/06 11:08:50 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
