# $FreeBSD: www/fr/releases/4.0R/Makefile,v 1.1 2003/12/15 16:05:00 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml notes.sgml errata.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
