#
# $FreeBSD: doc/ja_JP.eucJP/articles/zip-drive/Makefile,v 1.7 2004/10/28 18:37:19 rushani Exp $
#
# Article: IOmega ZIP Drivse
#
# Original revision: 1.4

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
