# $FreeBSD: www/ja/java/Makefile.inc,v 1.3 2000/11/07 11:37:55 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

WEBBASE?=	/data/ja/java
WEB_PREFIX?=	${.CURDIR}/../../..
