# $FreeBSD: www/en/layout/Makefile,v 1.1 2005/10/04 05:49:13 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		css
SUBDIR+=	images
SUBDIR+=	js

.include "${WEB_PREFIX}/share/mk/web.site.mk"
