# $FreeBSD: doc/el_GR.ISO8859-7/articles/greek-language-support/Makefile,v 1.1 2007/11/02 16:14:21 keramida Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
