#
# $FreeBSD: doc/el_GR.ISO8859-7/articles/contributing/Makefile,v 1.1 2009/05/01 13:17:56 keramida Exp $
#
# Article: Contributing to FreeBSD

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
