#
# $FreeBSD: doc/nl_NL.ISO8859-1/articles/contributing/Makefile,v 1.2 2008/12/28 16:49:46 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/contributing/Makefile
# %SRCID%	1.6
#
# Article: Contributing to FreeBSD

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
