#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/nl_NL.ISO8859-1/books/handbook/bsdinstall/Makefile,v 1.1 2011/11/04 21:04:42 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/bsdinstall/Makefile
# %SRCID%	1.1
#

CHAPTERS= 	bsdinstall/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
