#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD: doc/de_DE.ISO8859-1/articles/contributing/Makefile,v 1.2 2005/01/18 21:53:16 mheinen Exp $
#    $FreeBSDde: de-docproj/articles/contributing/Makefile,v 1.2 2005/01/06 20:22:43 mheinen Exp $
#    basiert auf: 1.6
#
# Article: FreeBSD unterstuetzen

DOC?= article

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
