# $FreeBSD: doc/el_GR.ISO8859-7/articles/problem-reports/Makefile,v 1.5 2008/08/21 19:21:32 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/problem-reports/Makefile
# %SRCID%	1.6

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

URL_RELPREFIX?= ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
