# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/linux-users/Makefile,v 1.1 2008/03/11 11:35:43 gabor Exp $
#
# Article: FreeBSD Quickstart for Linux Users

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
