# $FreeBSD: doc/es_ES.ISO8859-1/Makefile,v 1.10 2004/02/12 17:17:18 jesusr Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = es

DOC_PREFIX = ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
