#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/new-users/Makefile,v 1.5 2004/08/25 09:30:29 ale Exp $
#
# Articolo: Per chi e' alle Prime Armi sia con FreeBSD che con Unix
 
DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?= ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
