# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.7
#
# $FreeBSD: doc/pt_BR.ISO8859-1/Makefile,v 1.3 2003/12/29 04:28:54 lioux Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = pt_BR

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
