# $FreeBSD: doc/da_DK.ISO8859-1/articles/euro/Makefile,v 1.1 2003/03/09 21:25:19 blackend Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
