#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ru_RU.KOI8-R/books/handbook/filesystems/Makefile,v 1.1 2010/07/05 21:40:34 taras Exp $
# Original revision: 1.1
#

CHAPTERS= 	filesystems/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
