# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/ldap-auth/Makefile,v 1.1 2008/05/31 12:22:47 gabor Exp $
#
# Article: LDAP Authentication

MAINTAINER= kurin@causa-sui.net

DOC?=	article

FORMATS?= html-split html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
