#
# $FreeBSD: doc/hu_HU.ISO8859-2/articles/cups/Makefile,v 1.2 2010/11/28 19:23:07 pgj Exp $
#
# Article: CUPS on FreeBSD
#
# %SOURCE%  en_US.ISO8859-1/articles/cups/Makefile
# %SRCID%   1.2
#

NO_TIDY= yes

MAINTAINER= doc@FreeBSD.org

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
