# $FreeBSD: doc/el_GR.ISO8859-7/books/Makefile.inc,v 1.3 2008/09/01 22:35:08 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/Makefile.inc
# %SRCID%	1.4

DESTDIR?=	${DOCDIR}/el_GR.ISO8859-7/books/${.CURDIR:T}
