#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.2
#
# $FreeBSD: www/zh_CN/layout/css/Makefile,v 1.2 2007/01/15 21:09:02 delphij Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   fixed.css fixed_large.css global.css iefixes.css layout.css navigation.css table.css text.css query-pr.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
