# $FreeBSD: www/ja/developers/Makefile,v 1.1 2010/05/07 12:37:15 ryusuke Exp $
# Original Revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   cvs.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
