#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO8859-1/books/Makefile,v 1.4 2002/02/14 14:59:17 gioria Exp $
#    Original revision: 1.4
#

SUBDIR = faq
SUBDIR+= handbook
SUBDIR+= fdp-primer
SUBDIR+= developers-handbook
SUBDIR+= ppp-primer

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
