# $FreeBSD: www/fr/donations/Makefile,v 1.2 2003/12/15 16:09:26 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml wantlist.sgml donors.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
