# $FreeBSD: www/fr/snapshots/Makefile,v 1.1 2005/12/30 21:37:13 blackend Exp $
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
