# $FreeBSD: www/ja/releases/2.2R/Makefile,v 1.6 2011/02/26 06:04:53 ryusuke Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml
DOCS+=	install-media.sgml
DOCS+=	notes.sgml

### Revision checking
REVCHECK=	YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
