# $FreeBSD: www/ja/docs/Makefile,v 1.2 2010/07/15 11:21:35 ryusuke Exp $
# Original Revision: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
