# $FreeBSD: www/it/releases/4.11R/Makefile,v 1.1 2005/03/31 09:20:01 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  announce.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
