# $FreeBSD: www/en/releases/2.1.7R/Makefile,v 1.3 2004/04/06 11:32:24 phantom Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml
DOCS+=	notes.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
