# $FreeBSD: www/fr/docs/Makefile,v 1.1 2005/10/16 09:21:20 blackend Exp $
#
# The FreeBSD French Documentation Project
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml man.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
