#
# $FreeBSD: doc/el_GR.ISO8859-7/articles/linux-users/Makefile,v 1.2 2008/08/21 19:17:58 keramida Exp $
#
# ¶ρθρο:	FreeBSD: Γρήγορο ξεκίνημα για χρήστες Linux
#
# %SOURCE%	en_US.ISO8859-1/articles/linux-users/Makefile
# %SRCID%	1.1
#
DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
