#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/users/Makefile,v 1.1 2002/07/31 16:16:10 blackend Exp $
# $Id: Makefile,v 1.1 2002/07/30 08:43:01 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	users/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
