#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/de_DE.ISO8859-1/books/developers-handbook/policies/Makefile,v 1.2 2009/02/21 17:03:11 jkois Exp $
# $FreeBSDde: de-docproj/books/developers-handbook/policies/Makefile,v 1.2 2009/02/14 22:12:52 miwi Exp $
# basiert auf: 1.1
#

CHAPTERS= 	policies/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
