#       $FreeBSD: doc/fr_FR.ISO8859-1/Makefile,v 1.1 1999/11/10 21:28:21 nik Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = fr

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
