# $FreeBSD: doc/it_IT.ISO8859-15/Makefile,v 1.2 2002/09/22 11:07:24 blackend Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = it

DOC_PREFIX?= ${.CURDIR}/..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
