# The FreeBSD Documentation Project
# The FreeBSD Turkish Documentation Project
# $FreeBSD: www/tr/Makefile.inc,v 1.1 2003/12/01 21:26:21 blackend Exp $
# Original revision: 1.8


WEBBASE?=	/data/tr
WEB_PREFIX?=	${.CURDIR}/../..
