# $FreeBSD: www/es/copyright/Makefile,v 1.4 2007/11/07 09:01:09 gabor Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	freebsd-license.sgml
DOCS+=	daemon.sgml
DOCS+=	copyright.sgml

INDEXLINK= copyright.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
