#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD: doc/de_DE.ISO8859-1/Makefile,v 1.2 2004/12/18 12:48:34 jkois Exp $
#    $FreeBSDde: de-docproj/Makefile,v 1.2 2004/11/28 21:13:46 jkois Exp $
#    basiert auf:  1.7

COMPAT_SYMLINK = de

SUBDIR = articles
SUBDIR+= books

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
