# $FreeBSD: www/en/marketing/Makefile,v 1.3 2011/09/05 18:52:08 gjb Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
