# $FreeBSD: www/zh_CN/releases/Makefile.inc,v 1.1 2006/07/11 15:27:49 delphij Exp $
# The FreeBSD Simplified Chinese Documentation Project
# Original Revision 1.5

WEBBASE?=	/data/zh_CN/releases
WEB_PREFIX?=	${.CURDIR}/../../..
