#
# $FreeBSD: doc/el_GR.ISO8859-7/articles/gjournal-desktop/Makefile,v 1.2 2008/06/14 17:05:21 keramida Exp $
#
# Article: Implementing UFS journaling on a desktop PC
# 
# %SOURCE%	en_US.ISO8859-1/articles/gjournal-desktop/Makefile
# %SRCID%	1.1
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml
IMAGES_EN =	disklabel1.png
IMAGES_EN +=	disklabel2.png
URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
