# $FreeBSDde: de-www/ipv6/Makefile.inc,v 1.1 2011/06/13 21:33:54 jkois Exp $
# $FreeBSD: www/de/ipv6/Makefile.inc,v 1.1 2011/06/14 20:07:55 jkois Exp $
# basiert auf: 1.1

WEBBASE?=	/data/de/ipv6
WEB_PREFIX?=	${.CURDIR}/../../..
