#
#    The FreeBSD Hungarian Documentation Project
#    %SOURCE%    en_US.ISO8859-1/articles/Makefile.inc
#    %SRCID%     1.4
#
#    $FreeBSD: doc/hu_HU.ISO8859-2/articles/Makefile.inc,v 1.2 2008/06/25 11:28:03 gabor Exp $
#

DESTDIR?=	${DOCDIR}/hu_HU.ISO8859-2/articles/${.CURDIR:T}
