# Summary of work needed to support large disks and arrays.
#
# $FreeBSD: www/en/projects/bigdisk/Makefile,v 1.1 2004/09/12 18:33:10 scottl Exp $

MAINTAINER=	scottl

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
