#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ru_RU.KOI8-R/books/handbook/multimedia/Makefile,v 1.1 2004/04/05 13:29:01 den Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/handbook/multimedia/Makefile,v 1.4 2002/07/26 18:13:25 never Exp $
# Original revision: 1.2
#

CHAPTERS= 	multimedia/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
