# The FreeBSD Simplified Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: www/zh_CN/layout/Makefile,v 1.1 2006/07/11 15:27:48 delphij Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
