# $FreeBSD: www/el/FAQ/Makefile,v 1.1 2009/05/04 12:49:24 keramida Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   index.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
