# $FreeBSD: doc/mn_MN.UTF-8/books/handbook/advanced-networking/Makefile,v 1.1 2007/04/11 10:51:15 keramida Exp $
#
# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.2
#
# Build the Handbook with just the content from this chapter.
#

CHAPTERS= 	advanced-networking/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
