#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ja_JP.eucJP/books/handbook/bsdinstall/Makefile,v 1.1 2011/11/06 15:45:54 ryusuke Exp $
#

CHAPTERS= 	bsdinstall/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
