# $FreeBSD: www/fr/support/Makefile,v 1.1 2005/10/12 19:55:36 blackend Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   bugreports.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
