# $FreeBSD: doc/mn_MN.UTF-8/books/handbook/vinum/Makefile,v 1.1 2007/04/11 10:51:19 keramida Exp $
#
# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.1
#
# Build the Handbook with just the content from this chapter.
#

CHAPTERS= 	vinum/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
