#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/basics/Makefile,v 1.1 2002/07/29 17:53:34 blackend Exp $
# $Id: Makefile,v 1.1 2002/06/03 09:50:15 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	basics/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
