#
# The FreeBSD Traditional Chinese Project
# Original Revision: 1.4
#
# $FreeBSD: www/zh_TW/layout/css/Makefile,v 1.1 2007/06/05 08:36:09 chinsan Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	cvsweb.css
DATA+=	fixed.css
DATA+=	fixed_large.css
DATA+=	global.css
DATA+=	iefixes.css
DATA+=	layout.css
DATA+=	navigation.css
DATA+=	query-pr.css
DATA+=	table.css
DATA+=	text.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
