#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/dtrace/Makefile,v 1.1 2011/06/13 16:22:06 blackend Exp $
#

CHAPTERS= 	dtrace/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
