#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ru_RU.KOI8-R/books/handbook/network-servers/Makefile,v 1.1 2004/07/14 14:17:45 den Exp $
# $FreeBSDru$
#
# Original revision: 1.1

CHAPTERS= 	network-servers/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
