# $FreeBSD: doc/ru_RU.KOI8-R/man/man5/Makefile,v 1.1 2007/11/20 07:16:15 ru Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/man/man5/Makefile,v 1.2 2007/11/20 06:53:29 ru Exp $

MAN=	finger.conf.5

.include <bsd.prog.mk>
