# $FreeBSD: doc/sr_YU.ISO8859-2/articles/Makefile,v 1.2 2002/02/06 17:02:23 phantom Exp $

#SUBDIR = committers-guide
SUBDIR+= dialup-firewall
SUBDIR+= diskless-x
#SUBDIR+= explaining-bsd
#SUBDIR+= freebsd-questions
#SUBDIR+= fonts
#SUBDIR+= formatting-media
#SUBDIR+= ipsec-must
#SUBDIR+= mh
#SUBDIR+= multi-os
#SUBDIR+= new-users
#SUBDIR+= programming-tools
#SUBDIR+= zip-drive

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
