# $FreeBSD: www/hu/docs/Makefile,v 1.2 2007/08/05 21:05:27 gabor Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
