#!/bin/sh

# $Wintelcom: src/freebsd/pxe/doc/pre,v 1.1 2000/07/14 12:42:05 bright Exp $
# $FreeBSD: doc/fr_FR.ISO8859-1/articles/pxe/pre,v 1.1 2005/01/04 14:03:35 gioria Exp $

echo pre-install
exit 0
