# $FreeBSD: www/en/projects/mac/Makefile,v 1.1 2004/09/21 06:09:07 trhodes Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
