# $FreeBSD: www/ja/releases/8.2R/Makefile,v 1.1 2011/09/10 12:48:43 ryusuke Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml
#DOCS=	announce.sgml \
#	schedule.sgml \
#	relnotes.sgml

DATA=	docbook.css
#DATA=	docbook.css \
#	errata.html \
#	hardware.html \
#	readme.html \
#	relnotes-detailed.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
