# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Based on: 1.8
#
# $FreeBSD: www/pt_BR/Makefile.inc,v 1.1 2004/01/05 03:00:18 lioux Exp $

WEBBASE?=	/data/pt_BR
WEB_PREFIX?=	${.CURDIR}/../..
