#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ja_JP.eucJP/books/handbook/desktop/Makefile,v 1.1 2004/09/18 18:42:26 rushani Exp $
#
# Original revision: 1.1

CHAPTERS= 	desktop/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
