# $FreeBSD: www/el/Makefile.inc,v 1.2 2009/05/04 12:54:07 keramida Exp $
#
# The FreeBSD Greek Documentation Project
#
# %SOURCE%	en/Makefile.inc
# %SRCID%	1.8
#

WEBBASE?=	/data/el
WEB_PREFIX?=	${.CURDIR}/../..
