# $FreeBSD: doc/tr_TR.ISO8859-9/articles/explaining-bsd/Makefile,v 1.1 2003/10/04 10:06:30 blackend Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
