#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO8859-1/articles/Makefile.inc,v 1.3 2001/06/11 01:18:47 ache Exp $
#    Original revision: 1.2
#

DESTDIR?=	${DOCDIR}/fr_FR.ISO8859-1/articles/${.CURDIR:T}
