# 
# $FreeBSD: doc/nl_NL.ISO8859-1/articles/Makefile.inc,v 1.1 2008/11/10 21:09:59 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/Makefile.inc
# %SRCID%	1.4

DESTDIR?=	${DOCDIR}/nl_NL.ISO8859-1/articles/${.CURDIR:T}
