# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
# $FreeBSD: www/de/Makefile.inc,v 1.2 2003/08/10 19:51:58 mheinen Exp $
# $FreeBSDde: de-www/Makefile.inc,v 1.3 2003/05/11 17:32:43 mheinen Exp $
# basiert auf: 1.8

WEBBASE?=	/data/de
WEB_PREFIX?=	${.CURDIR}/../..
