#
# Build the Handbook with just the content from this chapter.
#
# %SOURCE%    en_US.ISO8859-1/books/handbook/filesystems/Makefile
# %SRCID%     1.1
#
# $FreeBSD: doc/hu_HU.ISO8859-2/books/handbook/filesystems/Makefile,v 1.1 2008/10/05 01:34:25 pgj Exp $
#

CHAPTERS= 	filesystems/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
