#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/mail/Makefile,v 1.1 2002/10/08 20:11:36 blackend Exp $
# $Id: Makefile,v 1.1 2002/09/26 18:57:37 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	mail/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
