#
# $FreeBSDde: de-www/FAQ/Makefile,v 1.2 2002/12/02 05:35:13 ue Exp $
# $FreeBSD: www/de/FAQ/Makefile,v 1.3 2002/12/06 21:57:48 ue Exp $
# Original revision:	1.8
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	index.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"

