#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ru_RU.KOI8-R/books/handbook/mail/Makefile,v 1.1 2004/03/26 13:38:12 den Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/handbook/mail/Makefile,v 1.1 2001/07/11 16:40:13 phantom Exp $
# Original revision: 1.1
#

CHAPTERS= 	mail/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
