#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/es_ES.ISO8859-1/books/handbook/firewalls/Makefile,v 1.1 2006/01/19 16:49:44 carvay Exp $
#

CHAPTERS= 	firewalls/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
