# $FreeBSD: www/en/snapshots/Makefile,v 1.1 2005/02/10 21:30:18 hrs Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
