# $FreeBSD: www/en/community/Makefile,v 1.2 2008/06/23 07:06:05 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.sgml mailinglists.sgml newsgroups.sgml webresources.sgml

XMLDOCS+=	social::${XML_EVENTS_EVENTS}:

.include "${WEB_PREFIX}/share/mk/web.site.mk"