# The FreeBSD Traditional Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: www/zh_TW/layout/Makefile,v 1.1 2007/06/05 08:36:09 chinsan Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
