# The FreeBSD Traditional Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: www/zh_TW/layout/Makefile.inc,v 1.1 2007/06/05 08:36:09 chinsan Exp $

WEBBASE?=	/data/zh_TW/layout
WEB_PREFIX?=	${.CURDIR}/../../..
