#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: www/ru/events/Makefile.inc,v 1.1 2005/06/18 05:59:33 andy Exp $
# $FreeBSDru: frdp/www/ru/events/Makefile.inc,v 1.1 2004/02/23 14:37:05 andy Exp $
#
# Original revision: 1.2
#

WEB_PREFIX?=	${.CURDIR}/../../..
WEBBASE?=	/data/ru/events
