# $FreeBSD: www/ja/snapshots/Makefile,v 1.1 2011/06/17 12:52:33 ryusuke Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
