# $FreeBSD: www/en/releases/2.2.2R/Makefile,v 1.4 2004/04/06 11:32:25 phantom Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	notes.sgml
DOCS+=	errata.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
