#!/bin/sh

# $Wintelcom: src/freebsd/pxe/doc/pre,v 1.1 2000/07/14 12:42:05 bright Exp $
# $FreeBSD: doc/es_ES.ISO8859-1/articles/pxe/pre,v 1.1 2009/09/27 13:06:32 gabor Exp $

echo pre-install
exit 0
