#
# Build the Handbook with just the content from this chapter.
#
# The FreeBSD Documentation Project
# The FreeBSD French Documentation Project
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/boot/Makefile,v 1.1 2002/08/02 13:45:39 blackend Exp $
# $Id: Makefile,v 1.1 2002/08/01 11:56:13 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	boot/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
