# $FreeBSD: www/fr/developers/Makefile,v 1.1 2005/11/02 21:39:11 blackend Exp $
# The FreeBSD French Documentation Project
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   cvs.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
