#
# $FreeBSD: doc/nl_NL.ISO8859-1/articles/problem-reports/Makefile,v 1.2 2008/12/28 12:23:36 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/problem-reports/Makefile
# %SRCID%	1.6
#
# Article: Writing FreeBSD Problem Reports

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
