#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/disks/Makefile,v 1.1 2003/06/09 13:49:17 blackend Exp $
# $Id: Makefile,v 1.1 2002/12/26 21:34:31 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	disks/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
