# 
# $FreeBSD: doc/ru_RU.KOI8-R/books/Makefile.inc,v 1.8 2001/12/12 11:49:37 phantom Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/Makefile.inc,v 1.3 2001/07/25 10:34:22 phantom Exp $
#
# Original revision: 1.4

DESTDIR?=	${DOCDIR}/ru_RU.KOI8-R/books/${.CURDIR:T}
