# $FreeBSD: doc/nl_NL.ISO8859-1/books/Makefile,v 1.2 2008/12/28 12:23:36 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/Makefile
# %SRCID%	1.14
#

SUBDIR = handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
