#
# $FreeBSD: doc/fr_FR.ISO8859-1/articles/contributing-ports/Makefile,v 1.1 2011/09/28 20:04:53 blackend Exp $
#
# Article: Contributing to the FreeBSD Ports Collection

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
