# $FreeBSD: www/en/layout/js/Makefile,v 1.2 2011/08/15 00:30:17 gjb Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   google.js \
	styleswitcher.js

.include "${WEB_PREFIX}/share/mk/web.site.mk"
