# $FreeBSD: doc/it_IT.ISO8859-15/books/Makefile,v 1.2 2003/03/19 19:19:44 trhodes Exp $

SUBDIR = handbook
SUBDIR+= unix-introduction

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
