#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO8859-1/books/Makefile.inc,v 1.2 2001/06/11 01:18:59 ache Exp $
#    Original revision: 1.2
#

DESTDIR?=	${DOCDIR}/fr_FR.ISO8859-1/books/${.CURDIR:T}
