# $FreeBSD: www/ja/FAQ/Makefile,v 1.8 2004/01/19 17:02:09 hrs Exp $
# Original revision:	1.8

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif
DATA=   index.html 

.include "${WEB_PREFIX}/share/mk/web.site.mk"
