#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: www/ru/portmgr/Makefile,v 1.1 2005/06/14 06:12:51 andy Exp $
# $FreeBSDru: frdp/www/ru/portmgr/Makefile,v 1.1 2005/06/13 06:43:35 andy Exp $
#
# Original revision: 1.1
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml charter.sgml policies.sgml qa.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
