#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/x11/Makefile,v 1.1 2002/07/29 17:53:40 blackend Exp $
# $Id: Makefile,v 1.2 2002/07/25 11:19:31 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	x11/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
