#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/eresources/Makefile,v 1.1 2002/09/15 20:04:14 blackend Exp $
# $Id: Makefile,v 1.1 2002/09/15 19:04:16 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	eresources/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
