#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/el_GR.ISO8859-7/books/handbook/filesystems/Makefile,v 1.1 2008/10/09 16:00:06 manolis Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/filesystems/Makefile
# %SRCID%	1.1
#

CHAPTERS= 	filesystems/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
