# $FreeBSD: www/it/docs/Makefile,v 1.1 2005/10/06 14:27:50 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS= books.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
