# $FreeBSD: www/fr/events/Makefile.inc,v 1.1 2004/03/06 17:33:18 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.2

WEB_PREFIX?=	${.CURDIR}/../../..
WEBBASE?=	/data/events
