#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: www/ru/snapshots/Makefile.inc,v 1.1 2005/06/10 06:24:00 andy Exp $
# $FreeBSDru: frdp/www/ru/snapshots/Makefile.inc,v 1.1 2005/06/08 16:46:01 andy Exp $
#
# Original revision: 1.1
#

WEBBASE?=	/data/ru/snapshots
WEB_PREFIX?=	${.CURDIR}/../../..
