#
# Crea il Manuale con il contenuto di solo questo capitolo.
#
# $FreeBSD: doc/it_IT.ISO8859-15/books/handbook/install/Makefile,v 1.2 2004/01/14 11:11:12 ale Exp $
#

CHAPTERS= 	install/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
