#
# Build the Handbook with just the content from this chapter.
#
# %SOURCE%    en_US.ISO8859-1/books/handbook/advanced-networking/Makefile
# %SRCID%     1.2
#
# $FreeBSD: doc/hu_HU.ISO8859-2/books/handbook/advanced-networking/Makefile,v 1.2 2008/06/25 11:28:05 gabor Exp $
#

CHAPTERS= 	advanced-networking/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
