# 
# $FreeBSD: doc/es_ES.ISO8859-1/articles/p4-primer/Makefile,v 1.1 2006/06/13 14:44:03 carvay Exp $
#
# Articulo sobre el uso de Perforce en el desarrollo en FreeBSD.

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
