# $FreeBSD: www/ja/news/Makefile.inc,v 1.2 2000/11/07 11:37:55 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

WEBBASE?=	/data/ja/news
WEB_PREFIX?=	${.CURDIR}/../../..
