# $FreeBSD: www/fr/FAQ/Makefile,v 1.1 2002/12/29 13:36:10 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.8

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   index.html 

.include "${WEB_PREFIX}/share/mk/web.site.mk"
