# $FreeBSD: doc/mn_MN.UTF-8/Makefile,v 1.1 2007/04/11 10:51:15 keramida Exp $
#
# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.7

#SUBDIR = articles
SUBDIR = books

COMPAT_SYMLINK = mn

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
