#
# $FreeBSD: doc/en_US.ISO8859-1/articles/cups/Makefile,v 1.2 2008/10/24 23:01:06 pgj Exp $
#
# Article: CUPS on FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
