#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/desktop/Makefile,v 1.1 2002/09/21 17:36:45 blackend Exp $
# $Id: Makefile,v 1.1 2002/09/21 16:45:53 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	desktop/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
