# $FreeBSD: www/zh_CN/news/Makefile.inc,v 1.1 2006/07/11 15:27:48 delphij Exp $
# The FreeBSD Simplified Chinese Documentation Project
# Original Revision: 1.2

WEBBASE?=	/data/zh_CN/news
WEB_PREFIX?=	${.CURDIR}/../../..
