#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/nl_NL.ISO8859-1/books/handbook/bibliography/Makefile,v 1.2 2008/12/28 12:23:37 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/bibliography/Makefile
# %SRCID%	1.1
#

CHAPTERS= 	bibliography/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
