# ACPI project page
#
# $FreeBSD: www/fr/projects/acpi/Makefile,v 1.1 2004/08/09 20:35:41 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.1

MAINTAINER=	marks

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
