# 
# $FreeBSD: doc/es_ES.ISO8859-1/articles/version-guide/Makefile,v 1.1 2008/02/03 15:02:16 carvay Exp $
#
# Article: FreeBSD Version Guide

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
