# $FreeBSD: www/es/news/Makefile,v 1.7 2007/11/07 09:01:10 gabor Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+= press.sgml
DOCS+= newsflash.sgml
DOCS+= news.sgml

# press releases
DOCS+= pressreleases.sgml
DOCS+= press-rel-1.sgml
DOCS+= press-rel-2.sgml
DOCS+= press-rel-3.sgml

INDEXLINK= news.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
