#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.4
# 
# $FreeBSD: doc/pt_BR.ISO8859-1/articles/Makefile.inc,v 1.1 2003/12/29 04:26:29 lioux Exp $
#

DESTDIR?=	${DOCDIR}/pt_BR.ISO8859-1/articles/${.CURDIR:T}
