#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/introduction/Makefile,v 1.1 2002/07/29 17:53:38 blackend Exp $
# $Id$
# Original revision: 1.1
#

CHAPTERS= 	introduction/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
