#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO8859-1/articles/Makefile,v 1.19 2009/06/07 13:26:03 blackend Exp $
#    Original revision: 1.3
#

SUBDIR = committers-guide
SUBDIR+= contributing
SUBDIR+= contributors
SUBDIR+= cvsup-advanced
SUBDIR+= dialup-firewall
SUBDIR+= diskless-x
SUBDIR+= euro
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= ip-aliasing
SUBDIR+= ipsec-must
SUBDIR+= java-tomcat
SUBDIR+= laptop
SUBDIR+= make-world
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= nanobsd
SUBDIR+= new-users
SUBDIR+= ntfs
SUBDIR+= pam
SUBDIR+= ppp
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= programming-tools
SUBDIR+= pxe
SUBDIR+= releng-packages
SUBDIR+= zip-drive

ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
