#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/nl_NL.ISO8859-1/books/handbook/jails/Makefile,v 1.2 2008/09/14 22:32:28 remko Exp $
#

CHAPTERS= 	jails/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
