# $FreeBSD: www/en/cgi/GnatsPR/Makefile,v 1.1 2011/07/25 07:35:42 hrs Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=	Section

DATA=	MIMEIterator.pm Section.pm

.include "${WEB_PREFIX}/share/mk/web.site.mk"
