# $FreeBSD: doc/el_GR.ISO8859-7/books/Makefile,v 1.3 2008/01/20 23:05:16 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/Makefile
# %SRCID%	1.14

SUBDIR = faq
SUBDIR+= handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
