# $FreeBSD: doc/el_GR.ISO8859-7/articles/Makefile.inc,v 1.3 2008/01/14 14:19:41 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/Makefile.inc
# %SRCID%	1.4

DESTDIR?=	${DOCDIR}/el_GR.ISO8859-7/articles/${.CURDIR:T}
