#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/ports/Makefile,v 1.1 2002/07/29 17:53:39 blackend Exp $
# $Id: Makefile,v 1.1 2002/07/02 12:48:55 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	ports/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
