# $FreeBSD: www/it/copyright/Makefile,v 1.1 2005/10/15 13:09:16 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  copyright.sgml

INDEXLINK= copyright.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
