#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ru_RU.KOI8-R/books/handbook/firewalls/Makefile,v 1.1 2005/05/22 09:59:47 marck Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/handbook/firewalls/Makefile,v 1.1 2004/12/15 14:37:20 den Exp $
# Original revision: 1.1
#

CHAPTERS= 	firewalls/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
