#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO8859-1/articles/problem-reports/Makefile,v 1.1 2002/06/08 09:59:07 gioria Exp $
#    Original revision: 1.1
#



DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
