# $FreeBSD: doc/sr_YU.ISO8859-2/articles/diskless-x/Makefile,v 1.1 2001/05/07 18:25:55 nik Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
