# $FreeBSD: www/fr/advocacy/Makefile,v 1.1 2002/12/29 13:36:10 stephane Exp $
#
# Makefile for the advocacy site

# The FreeBSD French Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml
DOCS+=	myths.sgml
# DOCS+=	letter.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
