# $FreeBSD: doc/fr_FR.ISO8859-1/articles/zip-drive/Makefile,v 1.1 2000/05/25 16:19:40 gioria Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
