# 
# $FreeBSD: doc/ru_RU.KOI8-R/articles/Makefile.inc,v 1.4 2001/12/12 11:49:37 phantom Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/Makefile.inc,v 1.4 2001/07/25 10:26:26 phantom Exp $
#
# Original revision: 1.3
#

DESTDIR?=	${DOCDIR}/ru_RU.KOI8-R/articles/${.CURDIR:T}
