# $FreeBSD: www/ja/projects/Makefile.inc,v 1.1 2005/01/10 02:17:26 rushani Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

WEBBASE?=	/data/ja/projects
WEB_PREFIX?=	${.CURDIR}/../../..
