# $FreeBSD: www/zh_TW/docs/Makefile,v 1.1 2007/08/24 04:12:07 chinsan Exp $

#########################################################
# The FreeBSD Traditional Chinese Documentation Project #
#########################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
