# $FreeBSD: doc/es_ES.ISO8859-1/articles/contributing/Makefile,v 1.1 2004/01/17 02:24:00 jesusr Exp $ 

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
