# $FreeBSD: doc/el_GR.ISO8859-7/Makefile,v 1.4 2008/01/14 14:19:41 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/Makefile
# %SRCID%	1.7

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = el

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
