#
# Build the Handbook with just the content from this chapter.
#
# %SOURCE%    en_US.ISO8859-1/books/handbook/audit/Makefile
# %SRCID%     1.1
#
# $FreeBSD: doc/hu_HU.ISO8859-2/books/handbook/audit/Makefile,v 1.2 2008/06/25 11:28:05 gabor Exp $
#

CHAPTERS= 	audit/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
