#
#  The FreeBSD Documentation Project
#  The FreeBSD Hungarian Documentation Project
#
#  $FreeBSD: doc/hu_HU.ISO8859-2/books/Makefile.inc,v 1.2 2008/06/25 11:28:04 gabor Exp $
#  %SOURCE%    en_US.ISO8859-1/books/Makefile.inc
#  %SRCID%     1.4
#

DESTDIR?=	${DOCDIR}/hu_HU.ISO8859-2/books/${.CURDIR:T}

