#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ja_JP.eucJP/books/handbook/multimedia/Makefile,v 1.2 2004/01/09 16:43:54 rushani Exp $
#
# Original revision: 1.2

CHAPTERS= 	multimedia/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
