# The FreeBSD Simplified Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: www/zh_CN/layout/Makefile.inc,v 1.1 2006/07/11 15:27:48 delphij Exp $

WEBBASE?=	/data/zh_CN/layout
WEB_PREFIX?=	${.CURDIR}/../../..
