#
# Crea il Manuale con il contenuto di solo questo capitolo.
#
# $FreeBSD: doc/it_IT.ISO8859-15/books/handbook/advanced-networking/Makefile,v 1.1 2002/09/22 11:07:43 blackend Exp $
#

CHAPTERS= 	advanced-networking/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
