# $FreeBSD: doc/nl_NL.ISO8859-1/articles/Makefile,v 1.8 2011/07/24 10:49:09 rene Exp $

# %SOURCE%	en_US.ISO8859-1/articles/Makefile
# %SRCID%	1.63

SUBDIR =
SUBDIR+= contributing
SUBDIR+= contributing-ports
SUBDIR+= explaining-bsd
SUBDIR+= problem-reports
SUBDIR+= solid-state

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
