#
# Build the Handbook with just the content from this chapter.
#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: doc/zh_CN.GB2312/books/handbook/filesystems/Makefile,v 1.1 2008/11/17 07:31:50 loader Exp $
#

CHAPTERS= 	filesystems/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
