# $FreeBSD: www/en/docproj/Makefile,v 1.11 2006/01/27 11:04:03 blackend Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.sgml 
DOCS+=	doc-set.sgml
DOCS+=	handbook.sgml
DOCS+=	handbook3.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml 
DOCS+=  translations.sgml
DOCS+=	docproj.sgml
DOCS+=	todo.sgml

INDEXLINK= docproj.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
