# $FreeBSD: www/de/ports/growth/Makefile,v 1.1 2007/04/01 11:09:38 jkois Exp $
# $FreeBSDde: de-www/ports/growth/Makefile,v 1.1 2007/03/31 14:27:07 jkois Exp $
# basiert auf: 1.2
#

TOOLDIR=${.CURDIR}/../../../tools/portsgrowth

all install clean:
	cd ${TOOLDIR}; \
		 ${MAKE} ${MAKEFLAGS} ${.TARGETS}

