#
# $FreeBSD: doc/ja_JP.eucJP/articles/problem-reports/Makefile,v 1.2 2004/10/28 18:37:19 rushani Exp $
#
# Article: Writing FreeBSD Problem Reports
#
# Original revision: 1.6

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
