#
# $FreeBSD: doc/ja_JP.eucJP/articles/diskless-x/Makefile,v 1.8 2004/10/28 18:37:18 rushani Exp $
#
# Article: Diskless X Server: a how to guide
#
# Original revision: 1.8

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
