# $FreeBSD: www/it/releases/5.4R/Makefile,v 1.1 2005/08/29 15:04:36 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  announce.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
