# $FreeBSD: doc/hu_HU.ISO8859-2/articles/explaining-bsd/Makefile,v 1.2 2008/06/25 11:28:03 gabor Exp $
#
# Article: Explaining BSD
#
# %SOURCE%    en_US.ISO8859-1/articles/explaining-bsd/Makefile
# %SRCID%     1.6
#

#
# Tidy messes up iso-8859-2 characters
#

NO_TIDY= yes

MAINTAINER= gabor@FreeBSD.org

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
