#
# $FreeBSD: doc/es_ES.ISO8859-1/articles/laptop/Makefile,v 1.2 2005/01/12 20:39:26 carvay Exp $
#
# Article about using FreeBSD on laptops
# "Article" sobre FreeBSD en computadoras portátiles.

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

#
WITH_ARTICLE_TOC?=YES


SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
