# $FreeBSD: www/fr/releng/Makefile,v 1.1 2003/12/15 16:04:58 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml charter.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
