# $FreeBSD: doc/it_IT.ISO8859-15/articles/Makefile,v 1.5 2004/08/25 09:30:28 ale Exp $

SUBDIR =
SUBDIR+= committers-guide
SUBDIR+= euro
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= vm-design

DOC_PREFIX?= ${.CURDIR}/../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
