# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# $FreeBSD: www/de/projects/Makefile.inc,v 1.1 2005/03/14 23:02:55 jkois Exp $
# $FreeBSDde: de-www/projects/Makefile.inc,v 1.1 2005/01/29 19:07:54 jkois Exp $
# basiert auf:  1.1

WEBBASE?=	/data/de/projects
WEB_PREFIX?=	${.CURDIR}/../../..
