# $FreeBSD: www/es/docproj/Makefile,v 1.3 2000/11/29 23:56:57 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.sgml 
DOCS+=	doc-set.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml 
DOCS+=  translations.sgml
DOCS+=	docproj.sgml

INDEXLINK= docproj.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
