# $FreeBSD: doc/es_ES.ISO8859-1/articles/fdp-es/Makefile,v 1.1 2007/09/01 18:40:50 carvay Exp $

MAINTAINER=carvay@es.FreeBSD.org

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
