#
# Crea il Manuale con il contenuto di solo questo capitolo.
#
# $FreeBSD: doc/it_IT.ISO8859-15/books/handbook/audit/Makefile,v 1.1 2005/08/29 13:25:41 ale Exp $
#

CHAPTERS= 	audit/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
