#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/filtering-bridges/Makefile,v 1.5 2004/08/25 09:30:28 ale Exp $
#
# Articolo: Filtering Bridges

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?= ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
