# $FreeBSD: www/ja/events/Makefile.inc,v 1.1 2010/01/20 15:51:38 ryusuke Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

WEB_PREFIX?=	${.CURDIR}/../../..
WEBBASE?=	/data/events
