#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/ja_JP.eucJP/books/handbook/l10n/Makefile,v 1.1 2001/07/19 16:25:25 hrs Exp $
#
# Original revision: 1.1

CHAPTERS= 	l10n/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
