#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: www/ru/projects/Makefile.inc,v 1.1 2004/01/26 07:15:29 andy Exp $
# $FreeBSDru: frdp/www/ru/projects/Makefile.inc,v 1.1 2004/01/25 12:59:37 andy Exp $
#
# Original revision: 1.1
#

WEBBASE?=	/data/ru/projects
WEB_PREFIX?=	${.CURDIR}/../../..
