# $FreeBSD: www/hu/events/Makefile.inc,v 1.2 2010/04/07 09:51:48 pgj Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################
# %SOURCE%    en/events/Makefile.inc
# %SRCID%     1.2

WEB_PREFIX?=	${.CURDIR}/../../..
WEBBASE?=	/data/hu/events
