# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/de_DE.ISO8859-1/books/developers-handbook/kerneldebug/Makefile,v 1.1 2009/02/14 22:06:22 miwi Exp $
# $FreeBSDde: de-docproj/books/developers-handbook/kerneldebug/Makefile,v 1.2 2007/08/31 06:13:09 as Exp $
# basiert auf: 1.1
#

CHAPTERS= 	kerneldebug/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
