# $FreeBSD: doc/bn_BD.ISO10646-1/articles/Makefile,v 1.1 2004/02/16 23:56:26 simon Exp $

SUBDIR = explaining-bsd
SUBDIR+= new-users

DOC_PREFIX?=	${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
