# $FreeBSD: doc/el_GR.ISO8859-7/articles/formatting-media/Makefile,v 1.4 2008/06/16 01:11:48 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/formatting-media/Makefile
# %SRCID%	1.8

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
