#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/vinum/Makefile,v 1.1 2002/10/24 16:56:45 blackend Exp $
# $Id: Makefile,v 1.1 2002/10/14 20:25:58 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	vinum/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
