#
# $FreeBSD: doc/ja_JP.eucJP/articles/contributing/Makefile,v 1.7 2004/10/28 18:37:18 rushani Exp $
#
# Article: Contributing to FreeBSD
#
# Original revision: 1.6

DOC?= article
WITH_ARTICLE_TOC?= YES

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
