#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/nl_NL.ISO8859-1/books/handbook/advanced-networking/Makefile,v 1.2 2008/12/28 12:23:36 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/advanced-networking/Makefile
# %SRCID%	1.2
#

CHAPTERS= 	advanced-networking/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
