# 
# $FreeBSD: doc/nl_NL.ISO8859-1/books/Makefile.inc,v 1.3 2008/12/28 12:23:36 rene Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/Makefile.inc
# %SRCID%	1.4
#

DESTDIR?=	${DOCDIR}/nl_NL.ISO8859-1/books/${.CURDIR:T}
