#
#    The FreeBSD Documentation Project
#    The FreeBSD Norwegian Documentation Project
#
#    $FreeBSD: doc/no_NO.ISO8859-1/books/Makefile,v 1.1 2004/08/23 19:13:17 trhodes Exp $
#

SUBDIR= handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
