#
# Crea il Manuale con il contenuto di solo questo capitolo.
#
# $FreeBSD: doc/it_IT.ISO8859-15/books/handbook/network-servers/Makefile,v 1.1 2004/08/25 09:30:31 ale Exp $
#

CHAPTERS= 	network-servers/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
