# $FreeBSD: www/ja/support/Makefile,v 1.2 2010/04/28 16:03:53 ryusuke Exp $
# Original Revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	bugreports.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
