#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/pl_PL.ISO8859-2/books/handbook/config/Makefile,v 1.1 2006/09/24 18:59:02 hrs Exp $
#

CHAPTERS= 	config/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
