#
# $FreeBSD: doc/el_GR.ISO8859-7/articles/compiz-fusion/Makefile,v 1.1 2008/06/05 08:09:49 manolis Exp $
#
# Article: Installing and using compiz-fusion
#
# %SOURCE%	en_US.ISO8859-1/articles/compiz-fusion/Makefile
# %SRCID%	1.1
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
