#
#    The FreeBSD Documentation Project
#    The FreeBSD Norwegian Documentation Project
#
#    $FreeBSD: doc/no_NO.ISO8859-1/books/Makefile.inc,v 1.1 2004/08/23 19:13:17 trhodes Exp $
#

DESTDIR?=	${DOCDIR}/no_NO.ISO8859-1/books/${.CURDIR:T}
