# $FreeBSD: doc/bn_BD.ISO10646-1/articles/new-users/Makefile,v 1.1 2004/02/16 23:56:26 simon Exp $

MAINTAINER= abulfazl@juniv.edu

DOC?=	article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "$(DOC_PREFIX)/share/mk/doc.project.mk"
