# $FreeBSD: doc/mn_MN.UTF-8/books/Makefile.inc,v 1.1 2007/04/11 10:51:15 keramida Exp $
#
# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.4

DESTDIR?=	${DOCDIR}/mn_MN.UTF-8/books/${.CURDIR:T}
