# $FreeBSD: doc/el_GR.ISO8859-7/articles/dialup-firewall/Makefile,v 1.4 2008/06/14 17:05:20 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/dialup-firewall/Makefile
# %SRCID%	1.5

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
