#
# $FreeBSD: doc/el_GR.ISO8859-7/articles/nanobsd/Makefile,v 1.1 2009/02/09 18:08:25 keramida Exp $
#
# Article: Introduction to NanoBSD

DOC?= article

FORMATS?= html

WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

# Images from the cross-document image library
IMAGES_LIB=  callouts/1.png
IMAGES_LIB+= callouts/2.png
IMAGES_LIB+= callouts/3.png
IMAGES_LIB+= callouts/4.png

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
