# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.10
#
# $FreeBSD: doc/pt_BR.ISO8859-1/books/Makefile,v 1.2 2002/10/01 03:06:50 lioux Exp $

SUBDIR+= faq

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
