#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: doc/ru_RU.KOI8-R/articles/cvsup-advanced/Makefile,v 1.1 2005/06/14 06:47:06 andy Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/cvsup-advanced/Makefile,v 1.3 2005/06/12 05:19:07 gad Exp $
#
# Original revision: 1.5
#
# Article: CVSup Advanced Points

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?=YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
