#
# $FreeBSD: doc/da_DK.ISO8859-1/articles/ipsec-must/Makefile,v 1.1 2004/07/12 13:09:30 blackend Exp $
#
# Article: Uafh&aelig;ngig Verifikation af IPsec Funktionalitet i FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
