#
# $FreeBSD: doc/es_ES.ISO8859-1/articles/euro/Makefile,v 1.1 2005/03/08 22:48:02 carvay Exp $
#
# Article: The Euro symbol on FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
