# $FreeBSDru: frdp/www/ru/support/Makefile,v 1.1 2005/11/03 21:27:23 gad Exp $
# $FreeBSD: www/ru/support/Makefile,v 1.1 2005/11/08 18:22:23 bvs Exp $
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   bugreports.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
