# $FreeBSD: www/it/releases/5.3R/Makefile,v 1.1 2005/01/08 11:53:24 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  announce.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
