# $FreeBSD: doc/es_ES.ISO8859-1/articles/linux-comparison/Makefile,v 1.1 2007/11/19 20:06:57 carvay Exp $
#
# Article: FreeBSD and Linux Comparison Whitepaper

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
