# $FreeBSD: www/fr/prstats/Makefile,v 1.2 2006/07/27 14:06:08 blackend Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
