# $FreeBSD: doc/sr_YU.ISO8859-2/articles/dialup-firewall/Makefile,v 1.1 2002/02/06 17:01:34 phantom Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
