# $FreeBSD: doc/el_GR.ISO8859-7/articles/new-users/Makefile,v 1.4 2008/08/21 19:17:20 keramida Exp $
#
# %SOURCE%	en_US.ISO8859-1/articles/new-users/Makefile
# %SRCID%	1.11

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

URL_RELPREFIX?= ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
