# $FreeBSD: doc/pt_BR.ISO8859-1/articles/Makefile,v 1.1 2003/12/29 04:27:53 lioux Exp $
#
# Build the FreeBSD FAQ
#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.36
#

SUBDIR =
SUBDIR+= contributing

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
