# $FreeBSD: www/en/releases/7.4R/Makefile,v 1.4 2011/02/24 19:56:46 hrs Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml \
	schedule.sgml

DATA=	docbook.css \
	errata.html \
	hardware.html \
	readme.html \
	relnotes.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
