# $FreeBSD: doc/es_ES.ISO8859-1/books/Makefile,v 1.4 2002/11/23 11:54:28 jesusr Exp $

SUBDIR = faq
SUBDIR+= handbook

ROOT_SYMLINKS = faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
