#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: doc/ru_RU.KOI8-R/articles/checkpoint/Makefile,v 1.2 2010/07/05 08:45:41 taras Exp $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/checkpoint/Makefile,v 1.1 2004/01/10 08:43:19 andy Exp $
#
# Original revision: 1.8
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml
IMAGES_EN=	networks.pic

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
