# Summary for C99 project status
#
# $FreeBSD: www/ja/projects/mips/Makefile,v 1.1 2005/01/10 02:17:26 rushani Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

MAINTAINER=	jmallett

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DATA=	style.css

### Revision checking
REVCHECK=	yes

.include "${WEB_PREFIX}/share/mk/web.site.mk"
