# $FreeBSD: www/zh_CN/releases/7.1R/Makefile,v 1.1 2009/01/05 07:00:58 delphij Exp $
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	docbook.css
DATA+=	errata.html
DATA+=	hardware.html
DATA+=	readme.html
DATA+=	relnotes.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
