# $FreeBSD: doc/da_DK.ISO8859-1/articles/Makefile,v 1.3 2004/07/12 13:09:30 blackend Exp $

SUBDIR = euro
SUBDIR+= ipsec-must
SUBDIR+= pxe


DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
