# $FreeBSD: www/it/releases/6.0R/Makefile,v 1.1 2005/11/17 10:05:07 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  announce.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
