# $FreeBSD: www/it/releases/4.10R/Makefile,v 1.2 2005/01/08 11:53:23 ale Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  announce.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
