# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.1
#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/mn_MN.UTF-8/books/handbook/filesystems/Makefile,v 1.1 2008/09/30 06:15:15 ganbold Exp $

CHAPTERS= 	filesystems/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
