#
# $FreeBSD: doc/ru_RU.KOI8-R/articles/gjournal-desktop/Makefile,v 1.2 2010/02/19 17:03:53 gabor Exp $
#
# Article: Implementing UFS journaling on a desktop PC
#
# Original revision: 1.1
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml
IMAGES_EN=	disklabel1.png
IMAGES_EN+=	disklabel2.png
URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
