# $FreeBSD: doc/no_NO.ISO8859-1/Makefile,v 1.1 2004/08/23 19:13:16 trhodes Exp $

#SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = no

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
