#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/kernelconfig/Makefile,v 1.1 2002/08/17 14:21:11 blackend Exp $
# $Id: Makefile,v 1.1 2002/08/07 16:22:03 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	kernelconfig/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
