# $FreeBSD: doc/sr_YU.ISO8859-2/Makefile,v 1.2 2002/02/06 16:56:15 phantom Exp $

SUBDIR = articles
#SUBDIR+= books

COMPAT_SYMLINK = sr

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
