# $FreeBSD: www/zh_CN/copyright/Makefile,v 1.1 2006/07/11 15:27:48 delphij Exp $
# Original Revision: 1.15

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	copyright.sgml
DOCS+=	daemon.sgml
DOCS+=	freebsd-doc-license.sgml
DOCS+=	freebsd-license.sgml
DOCS+=	license.sgml
DOCS+=	trademarks.sgml

INDEXLINK= copyright.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
