#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/mirrors/Makefile,v 1.1 2003/07/08 18:52:37 blackend Exp $
# $Id: Makefile,v 1.1 2003/07/08 18:46:17 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	mirrors/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
