# $FreeBSD: www/fr/community/Makefile,v 1.1 2005/10/12 12:29:17 blackend Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.sgml mailinglists.sgml newsgroups.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
