#
# $FreeBSD: doc/en_US.ISO8859-1/articles/linux-emulation/Makefile,v 1.1 2008/03/05 12:57:31 gabor Exp $
#
# Article: Linux emulation in FreeBSD

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
