#
# $FreeBSD: doc/en_US.ISO8859-1/articles/port-mentor-guidelines/Makefile,v 1.1 2011/07/20 17:50:26 tabthorpe Exp $
#
# Article: Port Mentor Guidelines
#

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
