# $FreeBSD: doc/mn_MN.UTF-8/books/handbook/bsdinstall/Makefile,v 1.1 2011/11/09 14:07:30 ganbold Exp $
#
# The FreeBSD Mongolian Documentation project
#
# Original revision: 1.1
#
# Build the Handbook with just the content from this chapter.
#

CHAPTERS= 	bsdinstall/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
