# Summary for C99 project status
#
# $FreeBSD: www/en/projects/c99/Makefile,v 1.2 2005/10/20 17:27:17 novel Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
