# 
# $FreeBSD: doc/es_ES.ISO8859-1/articles/casestudy-argentina.com/Makefile,v 1.1 2006/06/13 14:44:02 carvay Exp $
#
# Articulo: Estudio de caso de Argentina.com 

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
