#
# Build the Handbook with just the content from this chapter.
#
# %SOURCE%    en_US.ISO8859-1/books/handbook/vinum/Makefile
# %SRCID%     1.1
#
# $FreeBSD: doc/hu_HU.ISO8859-2/books/handbook/vinum/Makefile,v 1.2 2008/06/25 11:28:09 gabor Exp $
#

CHAPTERS= 	vinum/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
