#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/fr_FR.ISO8859-1/books/handbook/cutting-edge/Makefile,v 1.1 2002/12/26 21:33:02 blackend Exp $
# $Id: Makefile,v 1.1 2002/12/26 21:24:50 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	cutting-edge/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
