#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: www/ru/snapshots/Makefile,v 1.1 2005/06/10 06:23:25 andy Exp $
# $FreeBSDru: frdp/www/ru/snapshots/Makefile,v 1.1 2005/06/08 16:46:57 andy Exp $
#
# Original revision: 1.1
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
