# $FreeBSD: www/en/releases/4.2R/Makefile,v 1.2 2004/04/06 11:32:27 phantom Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml
DOCS+=	errata.sgml
DOCS+=	notes.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
