# 
# $FreeBSD: doc/ru_RU.KOI8-R/articles/geom-class/Makefile,v 1.2 2010/02/19 17:03:53 gabor Exp $
#
# Article: Writing a GEOM Class
#
# Original revision: 1.1
#

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
