#
# $FreeBSD: doc/ja_JP.eucJP/articles/fonts/Makefile,v 1.6 2004/10/28 18:37:18 rushani Exp $
#
# Article: Fonts and FreeBSD
#
# Original revision: 1.12

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
