# $FreeBSD: doc/hu_HU.ISO8859-2/Makefile,v 1.3 2008/06/25 11:28:03 gabor Exp $
# %SOURCE%    en_US.ISO8859-1/Makefile
# %SRCID%     1.7

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = hu

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
