# $FreeBSD: www/es/projects/Makefile,v 1.4 2001/11/13 09:40:03 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.sgml
DOCS+=	newbies.sgml

INDEXLINK= projects.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
