# $FreeBSD: www/hu/copyright/Makefile,v 1.1 2007/01/07 22:44:47 keramida Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	copyright.sgml

INDEXLINK= copyright.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
