# $FreeBSD: www/ja/releases/Makefile.inc,v 1.5 2000/11/07 11:37:57 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.5

WEBBASE?=	/data/ja/releases
WEB_PREFIX?=	${.CURDIR}/../../..
