# Summary for C99 project status
#
# $FreeBSD: www/fr/projects/c99/Makefile,v 1.1 2003/12/15 16:04:59 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.1

MAINTAINER=	mike

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
