# $FreeBSD: www/es/releases/Makefile,v 1.9 2007/11/19 20:43:18 carvay Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml snapshots.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
